# Server Properties ==================================================
server:
  port: 8090

# Spring Properties ================================================
spring:
  config:
    import:
     - classpath:/application-local.yml
     - classpath:/application-dev.yml
  profiles:
    group:
      "local": "local-setting"
      "dev": "dev-setting"
    active: local

  mail:
    host: smtp.gmail.com
    port: 465 # 465(SSL), 587(TLS)
    username: eansoftej@gmail.com
    password: # 구글계정-보안-앱 비밀번호

    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true

# jwt Properties ======================================================
jwt:
  secret: "dustmq"
  accessTokenExpireDate: 86400000 # 24시간 : 12 x 60 x 60 x 1000 (ms)
  refreshTokenExpireDate: 2592000000 # 30일 : 30 x 24 x 60 x 60 x 1000 (ms)